### ISSUE TITLE
2点軽微なエラーが出て動かなかったので報告用にIssue建てさせていただきました。

### ISSUE THREAD

**Issue by hanpen72** [DoranekoSystems/frida-medit#1]
【1点目】
questionsの2つ目の「find_data_type」のtypeが「checkbox」であるからか選択時に選択した項目の値を取得できていなかったので、typeを1つ目と同じ「rewlist」に設定したら2つ目に選択した値を正しく取得できるようになりました。

【2点目】
「for _type in data_type:」ここのfor-loopのところで、data_typeを「word」を選択した場合に1文字ずつのループになって次のif文でうまく処理が分岐できずエラーとなっていました。

上記2点修正したら自分の環境でうまく動き出しました。
どら猫さんいつも便利なツールありがとうございます。
他のツールもとても便利で助かっています。

**Comment by hanpen72** [comment]
どら猫さんすみません。自分が使い方間違ってたことによるエラーでしたOrz
checkboxはスペースでチェックして使うのですね。
そのままエンターで選択してたのが原因でエラー出ていました＾＾；
失礼しました。

**Comment by DoranekoSystems** [comment]
コメント有難うございます。凄く嬉しいです!
半日で作ったものなので、バグや改善要望などありましたら是非ご連絡頂けると幸いです。

**Comment by hanpen72** [comment]
了解です！新しいhexviewの機能もとても便利で感動しました；。；ﾜﾗ
