### ISSUE TITLE
mac環境でのmultiple_window

### ISSUE THREAD

**Issue by hanpen72** [DoranekoSystems/frida-medit#2]
自分の使用している環境がMacOSなのですがCREATE_NEW_CONSOLEが使えないらしくマルチ有効時にエラーとなってしまいました。
どら猫さんが気が向いたらで全然大丈夫ですので、もしご対応いただけたら嬉しく思います。(* .ˬ.)

**Comment by DoranekoSystems** [comment]
先ほどのcommitでmac対応いたしました。
ご確認いただければ幸いです。

**Comment by hanpen72** [comment]
どら猫さんご対応ありがとうございます。
対応早すぎて驚きました＞＜！
さっそくMacで動作確認したらエラーなく正しく動作すること確認できました！！
ありがとうございます。

そして、1点だけすごい細かいところなのですが自分VsCodeのターミナルを普段いつも使用していまして、どら猫さんのfrida-meditもVsCodeのターミナル(zsh)で使用しているのですが、VsCodeのターミナルだとマルチウィンドウの動作を確認するとエラー等は何も表示されないのですが新しい窓が開かない状態でどら猫さんなにか情報お持ちでしょうか＞＜？

お返事は明日以降のどら猫さんのお手好きのタイミングで全然大丈夫ですのでいただけると幸いです。

**Comment by hanpen72** [comment]
どら猫さんご確認ありがとうございます＞＜
大変失礼しました。
自分のvscode環境でも正常に動作していました！！
vscodeの真裏に言ってしまっていて新しいターミナルが起動していることに気づけませんでした＞＜
とても便利です；。；
